//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeNote
    {
        public System.Guid ChangeNoteId { get; set; }
        public int ChangeNoteNumber { get; set; }
        public int VersionNumber { get; set; }
        public string ChangeDescription { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public System.Guid Status { get; set; }
        public System.Guid ptrOriginationNote { get; set; }
    
        public virtual ChangeNoteState ChangeNoteState { get; set; }
        public virtual Document Document { get; set; }
        public virtual OriginationNote OriginationNote { get; set; }
    }
}
