//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChangeNoteState
    {
        public ChangeNoteState()
        {
            this.ChangeNotes = new HashSet<ChangeNote>();
        }
    
        public System.Guid ChangeNoteStateId { get; set; }
        public string Code { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<ChangeNote> ChangeNotes { get; set; }
    }
}
