//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerlServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class perlDbEntities : DbContext
    {
        public perlDbEntities()
            : base("name=perlDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChangeNote> ChangeNotes { get; set; }
        public DbSet<ChangeNoteState> ChangeNoteStates { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<OriginationNote> OriginationNotes { get; set; }
    }
}
