//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerlServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OriginationNote
    {
        public OriginationNote()
        {
            this.ChangeNotes = new HashSet<ChangeNote>();
        }
    
        public System.Guid OriginationNoteId { get; set; }
        public int OriginationNoteNumber { get; set; }
        public int RevisionNumber { get; set; }
        public string DocumentName { get; set; }
        public string DocumentDescription { get; set; }
        public int DocumentNumber { get; set; }
    
        public virtual ICollection<ChangeNote> ChangeNotes { get; set; }
    }
}
